spring.application.name=Inventory

eureka.client.service-url.defaultZone=http://eureka:8761/eureka

spring.datasource.url=jdbc:postgresql://postgres:5432/MAPPINGDB
spring.datasource.username=postgres
spring.datasource.password=1234567890

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

server.port=8083